services:
  - type: web
    name: ecopredict
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecopredict_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: ecopredict_db
    plan: free